services:
  spring-pdf-app-server:
    build:
      context: ./spring-pdf-app-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-pdf-api-sample-nw
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring-pdf-api
      SPRING_DATASOURCE_USERNAME: gara
      SPRING_DATASOURCE_PASSWORD: password

  mysql:
    image: mysql:8.4.5-oraclelinux9
    environment:
      MYSQL_USER: gara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: spring-pdf-api
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - spring-pdf-api-sample-nw
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  spring-pdf-api-sample-nw:
    driver: bridge
